export const ADD_FAVORITES = "ADD_FAVORITES";
export const DELETE_CHARACTER = "DELETE_CHARACTER";
export const ORDER = "ORDER"
export const FILTER = "FILTER"
export const GET_FAVORITES = "GET_FAVORITES"
export const REMOVE_FAVORITE = "REMOVE_FAVORITE"