export const ADD_FAVORITES = "ADD_FAVORITES";
export const ORDER = "ORDER"
export const FILTER = "FILTER"
export const GET_FAVORITES = "GET_FAVORITES"
export const REMOVE_FAVORITE = "REMOVE_FAVORITE"
export const GET_CHARACTER_DETAIL = "GET_CHARACTER_DETAIL"
export const CLEAN_DETAIL = "CLEAN_DETAIL"